api_version: v1
name: PCRF
spec:
  - applications:
      - vendor_id: VENDOR_ID_3GPP
        app_id: DIAMETER_APPLICATION_Gx
    mode: Server
    watchdog_timeout: 30
    transport_type: TCP
    local:
      ip_address: 127.0.0.1
      hostname: pcrf.epc.mynetwork.com
      realm: epc.mynetwork.com
      port: 3868
    peer:
      ip_address: 127.0.0.1
      hostname: pgw.epc.mynetwork.com
      realm: epc.mynetwork.com
      port: 3870